version: "2.4"
services:
    node:
      image: "node:jod-alpine3.21"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=development
      volumes:
        - ./:/home/node/app
      command: sh -c 'npm run dev'
      network_mode: host
