version: "2.4"
services:
    node:
      image: "node:15.8.0-alpine3.10"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
      ports:
        - "80:3000"
      command: "npm install start"
